version: "3.9"
services:
  server:
    image: deadunderscorememe/rtml-server:latest
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - mongo
    networks:
      - backend

  client:
    image: deadunderscorememe/rtml-client:latest
    ports:
      - "3000:3000"
    networks:
      - backend

networks:
  backend:
    driver: "bridge"
